### ISSUE TITLE
Judge Problem List

### ISSUE THREAD

**Issue by amirhamza05** [coderoj-dev/Online-Judge#44]
**Database**
name: judge_problems
```
problem_id 
is_accepted
user_id 
created_at 
updated_at
```
![Screenshot from 2021-06-13 22-03-28](https://user-images.githubusercontent.com/24900692/121814521-54ce5800-cc93-11eb-91dd-4852b0b701b5.png)

![Screenshot from 2021-06-13 22-03-41](https://user-images.githubusercontent.com/24900692/121814518-53049480-cc93-11eb-8e11-4f90284d0261.png)

![Screenshot from 2021-06-13 22-04-51](https://user-images.githubusercontent.com/24900692/121814533-67489180-cc93-11eb-9cb9-941bbdd9fae2.png)

**Comment by Jugal-Chanda** [comment]
#45
